class ServerCommands:
    # Команди клієнта
    REGISTER = "REGISTER"
    LOGIN = "LOGIN"
    CREATE_ROOM = "CREATE_ROOM"
    JOIN_ROOM = "JOIN_ROOM"
    SEND_MESSAGE = "SEND_MESSAGE"

    # Відповіді сервера
    AUTH_SUCCESS = "AUTH_SUCCESS"
    AUTH_ERROR = "AUTH_ERROR"
    REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS"
    ERROR = "ERROR"
    ROOM_CREATED = "ROOM_CREATED"