class ServerCommands:
    # Команди клієнта
    REGISTER = "REGISTER"
    LOGIN = "LOGIN"
    CREATE_ROOM = "CREATE_ROOM"
    JOIN_ROOM = "JOIN_ROOM"
    SEND_MESSAGE = "SEND_MESSAGE"
    UPDATE_SETTINGS = "UPDATE_SETTINGS"
    READY_TOGGLE = "READY_TOGGLE"
    GET_ROOM_STATE = "GET_ROOM_STATE"
    GAME_ACTION = "GAME_ACTION"

    # Відповіді сервера
    AUTH_SUCCESS = "AUTH_SUCCESS"
    AUTH_ERROR = "AUTH_ERROR"
    REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS"
    ERROR = "ERROR"
    ROOM_CREATED = "ROOM_CREATED"
    ROOM_STATE = "ROOM_STATE"
    GAME_START = "GAME_START"
